# Generated by Django 3.1.7 on 2021-03-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('courseNumber', models.IntegerField(max_length=10)),
                ('instructor', models.CharField(max_length=60)),
                ('duration', models.FloatField(max_length=20)),
            ],
        ),
    ]
